export enum ActionTypes {
  INCREASE_COFFEE = 'INCREASE_COFFEE',
  DECREASE_COFFEE = 'DECREASE_COFFEE',
  ADD_TO_CART = 'ADD_TO_CART',
  INCREASE_PERM_COFFEE = 'INCREASE_PERM_COFFEE',
  DECREASE_PERM_COFFEE = 'DECREASE_PERM_COFFEE',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  CONFIRM_REQUEST = 'CONFIRM_REQUEST',
}
