export enum CartActionTypes {
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  INCREASE_PERM_COFFEE = 'INCREASE_PERM_COFFEE',
  DECREASE_PERM_COFFEE = 'DECREASE_PERM_COFFEE',
  CONFIRM_REQUEST = 'CONFIRM_REQUEST',
}
